---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeflow-trainer-cache-initializer
rules:
  - apiGroups:
      - leaderworkerset.x-k8s.io
    resources:
      - leaderworkersets
    verbs: ["create", "get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - services
    verbs: ["create", "get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs: ["create", "delete", "get", "list", "watch"]
